config/routes.rb
Pad::Application.routes.draw do

  get "home/index"
  root :to => "home#index"

  resources :clients do
    resources :appointments
  end

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :client
  attr_accessible :date, :notes, :time

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :address, :name, :notes, :phone_number

  validates :name, :presence => true

  has_many :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def create
    @client = Client.find(params[:client_id])
    @appointment = @client.appointments.create(params[:appointment])
    redirect_to client_path(@client)
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Phone number</th>
    <th>Address</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><%= client.name %></td>
    <td><%= client.phone_number %></td>
    <td><%= client.address %></td>
    <td><%= client.notes %></td>
    <td><%= link_to 'Show', client %></td>
    <td><%= link_to 'Edit', edit_client_path(client) %></td>
    <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Client', new_client_path %>
<br />
<%= link_to 'Home', '/' %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @client.name %>
</p>

<p>
  <b>Phone number:</b>
  <%= @client.phone_number %>
</p>

<p>
  <b>Address:</b>
  <%= @client.address %>
</p>

<p>
  <b>Notes:</b>
  <%= @client.notes %>
</p>

<h2>Appointments:</h2>
<% @client.appointments.each do |appointment| %>
  <p>
    <b>Date:</b>
    <%= appointment.date %>
  </p>
  <p>
    <b>Time:</b>
    <%= appointment.time %>
  </p>
  <p>
    <b>Notes:</b>
    <%= appointment.notes %>
  </p>
<% end %>

<h2>Add an appointment:</h2>
<%= form_for([@client, @client.appointments.build]) do |f| %>
  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :time %>
    <%= f.time_select :time %>
  </div>

  <br />

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>

  <div class="action">
    <%= f.submit %>
  </div>
    
<% end %>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/home/index.html.erb
<h1>PAD - People And Dates</h1>
<p>
This is the home page of the PAD application.  Use the links below!
</p>

<%= link_to "Clients", clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pad</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>